pagopa/site-pagopa.gov.it

- it/pubbliche-amministrazioni/come-aderire.md
> Modifica da pec e e-mail

- it/pagopa-spa/societa-trasparente/selezione-del-personale/reclutamento-del-personale/lavora-con-noi/chief-communication-officer.md
- it/pagopa-spa/societa-trasparente/selezione-del-personale/reclutamento-del-personale/lavora-con-noi/product-owner.md
> Add Product owner.

- it/pagopa/linee-guida.md
> Modifica doc linee guida

- _data/roadmap.yml
> cambio data delivery gest.convenzioni

- _includes/dashboard.html
- _includes/meta.html
- it/pagopa/dashboard.md
> Migliorata gestione description in SEO.

- it/pagopa-spa/societa-trasparente/selezione-del-personale/reclutamento-del-personale/lavora-con-noi/junior-software-engineer.md
Da definire il corretto url di Jazz prima di effettuare il merge.
> Nuova posizione - Junior Software Engineer

- it/pagopa/documentazione.md
Promossa Tassonomia dei Servizi di incasso (monografia e tabella tassonomica) dalla consultazione.
> update - Tassonomia servizi di incasso definitiva

- it/pagopa/documentazione.md
Published v2.0 of "Processo di pagamento presso il PSP con Ente multibeneficiario" and removed it from "Documentazione in consultazione" section.
> rimozione dalla consultazione - Monografia nuovo mod.3

- it/pagopa/documentazione.md
> removed update date from first page

- it/pagopa/documentazione.md
Fixed a broken link to new SANP-2.4.0 in "Documentazione" page.
> fixed broken link for new SANP release

- it/accessibilita-piattaforma.md
- it/accessibilita.md
Accessibility declaration link update
> [WEB-125] Link update

- it/dove-pagare.md
This PR updates the PSP list link
> [WEB-132] Update dove-pagare.md

- _data/pa-documentazione.yml
- _data/psp-documentazione.yml
- updated GitHub links
- removed link from PSP page
> [GOV-128] Fixes

- it/dashboard.md
Try to add  `/it/dashboard/` to dashboard `redirect_from`
> Add `/it/dashboard/` redirect_from

- it/dashboard.md
Reverts pagopa/site-pagopa.gov.it#426
> Revert "Avoid generating _site/it/pagopa/dashboard"

- _posts/2021-03-01-nuovo-modello-multibeneficiario.md
- _posts/2021-03-09-tari-tefa.md
- _posts/2021-04-01-canone-unico.md
- _posts/2021-05-10-anticipo-ricevute-telematiche.md
- _posts/2021-08-03-tari-milano-pagopa.md
This PR adds captions for the post images published so far.
(Unsplash license doesn't require it, still it's nice to acknowledge the authors)
> [GOV-139] Added captions

- it/pubbliche-amministrazioni/come-aderire.md
This PR adds a link to CBILL page where users can inquiry CBILL Codes DB
> [GOV-144] Update come-aderire.md

- it/prestatori-servizi-di-pagamento/come-aderire.md
This PR changes some text in "Come aderire" page for PSPs.
> [GOV-145] Update come-aderire.md

- it/cittadini/vantaggi.md
This PR updates a broken link in "Vantaggi" page
> [GOV-153] Update vantaggi.md

- _data/pa-documentazione.yml
- _data/psp-documentazione.yml
> [GOV-156] SANP link fix

- _data/pa-documentazione.yml
This PR adds the link to the taxonomy survey
> [GOV-158] Update pa-documentazione.yml

- it/pubbliche-amministrazioni/come-aderire.md
> [GOV-171] Update come-aderire.md

- _data/t.yml
- _includes/banner-app.html
- _includes/header/header-navigation.html
- _includes/hero.html
- assets/main.js
> Iopay 382  iopay 385

- it/pubbliche-amministrazioni/partner-intermediari.md
> [GOV-175] Update partner-intermediari.md

- it/accessibilita-piattaforma.md
- it/helpdesk.md
- it/pubbliche-amministrazioni/come-aderire.md
- it/pubbliche-amministrazioni/obbligatorieta.md
This PR updates support email address and phone number.
To be merged on 31\12\21
> [GOV-178] Help content update

- _includes/components/grid-posts.html
This PR fixes the CTA within the news list
> [GOV-201] Update grid-posts.html

- _data/psp-outofdate.yml
Eliminazione del PSP FactorCoop dalla BL
> Aggiornamento BL PSP NM3

- _data/pa-documentazione.yml
- _data/psp-documentazione.yml
- New SANP 3.0 Link
- Removed "specifiche di connessione"
- Removed "indicatori qualità"
> [GOV-211, GOV-212, GOV-213] Documentation Update

- _data/pa-documentazione.yml
- _data/psp-documentazione.yml
This PR removes the outdated "Monografia POS"
> Documentation update

- _data/pa-documentazione.yml
- _data/psp-documentazione.yml
- removed "tassa automobilistica"
- changed URL for "Tassonomia"
- removed deprecated API link
> [GOV-223, PSD-152] Documentation update

- _data/pa-documentazione.yml
- _data/psp-documentazione.yml
This PR updates the brand documentation links in the documentation pages
> [GOV-229] New brand documentation

- _data/psp-outofdate.yml
Remove Banca Popolare Pugliese from Outdated list
> [GOV-245] Update psp-outofdate.yml

- _data/t.yml
This PR replaces the outdated link to "Piano Triennale".
> [GOV-250] Replace outdated link

- it/pubbliche-amministrazioni/come-aderire.md
- style.scss
Here below is the resulting page:
Width=980
Width=393
> [Gov 251] Review come aderire page

- _data/pa-documentazione.yml
- _data/psp-documentazione.yml
- _posts/2022-02-21-pubblicazione-SACI.md
- _posts/2022-02-28-avviso-di-pagamento.md
- _posts/2022-05-26-Nuove-SANP.md
- _posts/2022-07-13-nuove-SACI.md
- _posts/2023-01-10-linee_guida_uso_marchio.md
- _posts/2023-04-21-sanp3_4_0.md
- _posts/2023-12-06-new_sanp_saci.md
- it/prestatori-servizi-di-pagamento/come-aderire.md
- it/pubbliche-amministrazioni/come-aderire.md
Replaced any occurrence to docs.pagopa.it with their equivalents on the developer portal.
Technical contents need to be published on the PagoPA's Developer Portal.
Manually
> [B2BP-228]  Migrate links from docs.pagopa.it to developer.pagopa.it

- it/sospensione-accesso-tramite-spid.md
This page will be used by WISP starting from May 9th. It is intended to be reachable only by a specific alert on WISP website, so it won't be indexed nor added to any menu of pagoPA website
> [GOV-256] Create disclaimer page about temporary unavailability of login with SPID on WISP website

- it/sospensione-accesso-tramite-spid.md
- style.scss
This PR adds translations for English, German, French, and Slovenian.
> [GOV-256] Translations for the SPID access suspension page

- _data/pa-documentazione.yml
Update link to Gazzetta Ufficiale
> [GOV-260] Update link to GU

- _layouts/default.html
- assets/main.js
Replace the deprecated BE endpoint to signup the newsletter
Fix
Manually
> [B2BP-708] Change the BE endpoint to subscribe the newsletter

- _includes/banner-app.html
This PR updates some content in the "dove pagare" page, expanding the available methods on checkout.pagopa.it
> Update "dove pagare" content

- assets/main.js
The check is based on the POST result code only
The new BE returns a different statusText than the previous one.
Manually
None
> [B2BP-759] Fix the newsletter endpoint result check after BE migration

- _data/psp-canali-pagamento.yml
- _data/psp-metodi.yml
- _includes/components/trasparenza-costi.html
Fix the Worldpay cards for the app IO's payment channel
Fix
Manually
> [B2BP-959] Handle the worldpay cards

- it/assistenza.md
Updated the assistance landline number
Changed the phone number
Manually
> Update the assistance landline phone number

- it/assistenza.md
> [B2BP-561] Revert the applied PR

- it/assistenza.md
This PR has to be merged on the 1st of October 2024 and updates the assistance landline phone number.
> [B2PB-561] Update the assistance landline phone number

- .github/workflows/deploy-aws.yaml
Force Ubuntu 22.04 in the build pipeline
The build process suddenly started to fail saying "Unsupported platform ubuntu-24.04"
(see https://github.com/pagopa/site-pagopa.gov.it/actions/runs/11345609957).
Manually
None
> [B2BP-996] Update deploy-aws.yaml

- _data/psp-documentazione.yml
> [B2BP-1032] Fix link to the PSP pdf in the docs page

- _posts/2024-11-15-evoluzioni-sistema-pagamento.md
> [B2BP-1035] Remove duplicated title in the NPG news

- _includes/psp-servizi.html
This PR changes a small label shown in PSP detail page
> Small label change

- it/pubbliche-amministrazioni/partner-intermediari-elenco.md
Remove the initial paragraph in the pt list page
> [B2BP-1132] Remove the initial paragraph in the pt list page

- it/pubbliche-amministrazioni/partner-intermediari-elenco.md
Add the description to the PT list page
> [B2BP-1135] Add the description to the PT list page

- _data/t.yml
- it/accessibilita.md
Update the link to the a11y Agid form
> [B2BP-1140] Update the a11y link

- _includes/header/header-navigation.html
Same as the title
Update site contents
Run locally on localhost:4000
> [B2BP-1239] - Add new service link

- _data/partner-dettagli.yml
> [B2BP-1334] Add new entry in partner-dettagli.yml

- it/prestatori-servizi-di-pagamento/elenco-PSP-attivi.md
- it/prestatori-servizi-di-pagamento/trasparenza-bancaria.md
This PR adds a new page listing all the legal documents provided by PSPs.
> New trasparenza bancaria page

- it/prestatori-servizi-di-pagamento/elenco-PSP-attivi.md
- it/prestatori-servizi-di-pagamento/trasparenza-bancaria.md
This PR fixes a broken CTA in the PSP page, including some cosmetic fixes related to CSS
> Fix psp broken link

- _data/pa-documentazione.yml
Same as the title
Update website content
Ran locally on localhost:4000
> [B2BP-1339] - Removal of broken link “Taxonomy survey”
